logging:
  level:
    mx:
      com:
        beethub:
          receipt: DEBUG
spring:
  application:
    name: receipt-api
  datasource:
    url: jdbc:mysql://${DB_URL:localhost}/${DB_NAME:local-db}
    username: ${DB_USER:local-user}
    password: ${DB_PASSWORD:local-pass}
  jpa:
    show-sql: true
  flyway:
    enabled: false
